- type: job
  id: Paramedic
  name: job-name-paramedic
  description: job-description-paramedic
  playTimeTracker: JobParamedic
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 3600 #1 час Ganimed
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 18000 #5 часа Ganimed
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 42000 #11,6 часов Ganimed
  startingGear: ParamedicGear
  icon: "JobIconParamedic"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - External
  extendedAccess:
  - Chemistry

- type: startingGear
  id: ParamedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitParamedic
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorWhite
    id: ParamedicPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltParamedicFilled
  innerclothingskirt: ClothingUniformJumpskirtParamedic
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
