- type: startingGear
  id: JanitorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitJanitor
    back: ClothingBackpackFilled
    shoes: ClothingShoesGaloshes
    head: ClothingHeadHatPurplesoft
    id: JanitorPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
  innerclothingskirt: ClothingUniformJumpskirtJanitor
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: startingGear
  id: JanitorMaidGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtJanimaid
    back: ClothingBackpackFilled
    id: JanitorPDA
    head: ClothingHeadHatCatEars
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
  innerclothingskirt: ClothingUniformJumpskirtJanimaid
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
