- type: startingGear
  id: MusicianGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMusician
    back: ClothingBackpackMusicianFilled
    eyes: ClothingEyesGlassesSunglasses
    shoes: ClothingShoesBootsLaceup
    id: MusicianPDA
    ears: ClothingHeadsetService
  satchel: ClothingBackpackSatchelMusicianFilled
  duffelbag: ClothingBackpackDuffelMusicianFilled
