- type: startingGear
  id: BoxerGear
  equipment:
    jumpsuit: UniformShortsRed
    back: ClothingBackpackFilled
    id: BoxerPDA
    ears: ClothingHeadsetService
    gloves: ClothingHandsGlovesBoxingRed
    shoes: ClothingShoesColorRed
    belt: ClothingBeltChampion
  innerclothingskirt: UniformShortsRedWithTop
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
