- type: department
  id: Civilian
  description: department-Civilian-description
  color: "#acabad"
  roles:
  - Civilian
  - Survivor

- type: department
  id: Foresters
  description: department-Foresters-description
  color: "#79a066"
  roles:
  - Hunter
  - Ranger

- type: department
  id: Facility
  description: department-Facility-description
  color: "#8ab5bc"
  roles:
  - Technician
  - Scientist
  - Engineer
  - Manager

- type: department
  id: Security
  description: department-Security-description
  color: "#d72d1d"
  roles:
  - Chief
  - Officer
  - Medic

- type: department
  id: Special
  description: department-Special-description
  color: "#e1ca96"
  roles:
  - Butcher
  - Zombie
  - Monster
  - Paramedic
