- type: job
  id: BlueShield
  name: job-name-blueshield
  description: job-description-blueshield
  playTimeTracker: JobBlueShield
  requirements:
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 28800 #8h
    - !type:DepartmentTimeRequirement
      department: Command
      time: 28800 #8h
  startingGear: BlueShieldGear
  icon: "JobIconBlueShield"
  supervisors: job-supervisors-command
  canBeAntag: false
  access:
  - Command
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Engineering
  - Research
  - Detective
  - Security
  - Brig
  - Cargo
  - Medical
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  sponsorOnly: true

- type: startingGear
  id: BlueShieldGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBlueShield
    back: ClothingBackpackSecurityBlueShieldFilled
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesBlueShield
    head: ClothingHeadHatBeretBlueShield
    outerClothing: ClothingOuterCoatBlueShield
    neck: ClothingNeckTieBlueShield
    id: BlueShieldPDA
    mask: ClothingMaskNeckGaiter
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetCommand
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponRevolverDeckard
  innerClothingskirt: ClothingUniformJumpskirtBlueShield
  satchel: ClothingBackpackSatchelSecurityBlueShieldFilled
  duffelbag: ClothingBackpackDuffelSecurityBlueShieldFilled
