- type: job
  id: IAA
  name: job-name-iaa
  description: job-description-iaa
  playTimeTracker: JobIAA
  requirements:
  - !type:DepartmentTimeRequirement
    department: Command
    time: 43200 #12h
  - !type:RoleTimeRequirement
    role: JobLawyer
    time: 28800 #8h
  startingGear: IAAGear
  icon: "JobIconIAA"
  supervisors: job-supervisors-centcom
  weight: 10
  requireAdminNotify: true
  joinNotifyCrew: true
  canBeAntag: false
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  access:
  - Service
  - Brig
  - Maintenance
  - Command
  - External
  - Lawyer

- type: startingGear
  id: IAAGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerGood
    back: ClothingBackpackFilled
    shoes: ClothingShoesBootsLaceup
    id: IAAPDA
    eyes: ClothingEyesGlassesSunglasses
    neck: ClothingNeckLawyerbadge
    ears: ClothingHeadsetIAA
    pocket1: RubberStampIAA
  inhand:
    - BriefcaseBrownLegalFilled
  innerClothingskirt: ClothingUniformJumpskirtLawyerBlack
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
