- type: entity
  save: false
  parent: [ BaseSimpleMob, MobCombat ]
  id: BaseMobMonster
  description: A dangerous alien found on the wrong side of planets, known for their high levels of intelligence.
  suffix: "Monster"
  abstract: true
  components:
  - type: IntrinsicRadioReceiver
  - type: IntrinsicRadioTransmitter
    channels:
    - Monster
  - type: ActiveRadio
    channels:
    - Monster
  - type: NpcFactionMember
    factions:
    - Xeno
  - type: Sprite
    sprite: Mobs/Aliens/Argocyte/argocyte_common.rsi
    drawdepth: Mobs
  - type: SolutionContainerManager
  - type: Monster
  - type: ReplacementAccent
    accent: xeno
  - type: Bloodstream
    bloodReagent: FerrochromicAcid
    bloodMaxVolume: 200
    bloodlossDamage:
      types:
        Bloodloss:
          1
    bloodlossHealDamage:
      types:
        Bloodloss:
          -1
  - type: Insulated
  - type: CombatMode
  - type: MeleeWeapon
    angle: 0
    animation: WeaponArcBite
    damage:
      types:
        Slash: 5
  - type: Body
    prototype: Animal
  - type: Flammable
    fireSpread: true
    canResistFire: true
    damage:
      types:
        Heat: 3
  - type: FireVisuals
    sprite: Mobs/Effects/onfire.rsi
    normalState: Generic_mob_burning
  - type: Climbing
  - type: Flashable
  - type: NameIdentifier
    group: GenericNumber
  - type: UserInterface
    interfaces:
    - key: enum.MonsterEvolutionMenuKey.Key
      type: MonsterEvolutionBoundUserInterface
  - type: IntrinsicUI
    uis:
    - key: enum.MonsterEvolutionMenuKey.Key
      toggleAction: ActionMonsterEvolutionMenu
  - type: MobThresholds
    thresholds:
      0: Alive
      15: Critical
      30: Dead
  - type: Stamina
    critThreshold: 60
  - type: Blindable
    isBlind: true

- type: entity
  id: MobMonsterEgg
  name: egg
  description: You certainly don't want to know what it looks like hatched.
  components:
  - type: Sprite
    sprite: Objects/Consumable/Food/egg.rsi
    state: icon
    scale: 1.35, 1.35
    noRot: true
  - type: Damageable
    damageModifierSet: Zombie
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 100
      behaviors:
      - !type:SpawnEntitiesBehavior
        spawn:
            PuddleEgg:
              min: 4
              max: 4
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: Blindable
    isBlind: true
  - type: Clickable
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.3
        density: 50
        mask:
        - MobMask
        layer:
        - MobLayer
  - type: Flammable
    fireSpread: true
    canResistFire: true
    damage:
      types:
        Heat: 3
  - type: IntrinsicRadioReceiver
  - type: ActiveRadio
    channels:
    - Monster