- type: job
  id: ScientistBase
  name: job-name-scientist-base
  description: job-description-scientist-base
  playTimeTracker: JobScientistBase
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 18000 #5 hrs
  startingGear: ScientistBaseGear
  icon: "JobIconScientistBase"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance

- type: startingGear
  id: ScientistBaseGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitScientist
    back: ClothingBackpackScienceFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatRnd
    id: SciencePDA
    ears: ClothingHeadsetScience
  innerClothingSkirt: ClothingUniformJumpskirtScientist
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled
