- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  color: "#D381C9"
  playTimeTracker: JobResearchDirector
  requirements:
    - !type:RoleTimeRequirement
      role: JobSeniorResearcher
      time: 14400 #4h
    - !type:DepartmentTimeRequirement
      department: Science
      time: 86400 #24h
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Brig
  special:
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    back: ClothingBackpackResearchDirectorFilled
    shoes: ClothingShoesColorBrown
    outerClothing: ClothingOuterCoatRD
    id: RnDPDA
    ears: ClothingHeadsetRD
  innerClothingSkirt: ClothingUniformJumpskirtResearchDirector
  satchel: ClothingBackpackSatchelResearchDirectorFilled
  duffelbag: ClothingBackpackDuffelResearchDirectorFilled
